### ISSUE TITLE
one more step to README.md...   or a link to another page.

### ISSUE THREAD

**Issue by eric-schleicher** [luxonis/DepthAI-PyFlow#2]
I was able to follow the instructions to install pyflow and to set the folder for the depthAI node library.

I wasn't able to wire up a simple example where i just flow the RGB to a preview node.   Not totally sure if I had configured the underlying connection to the device correctly.. or if there are other properties on the 1098OBC required to get it running.

my feeble graph attempt
![image](https://user-images.githubusercontent.com/8261783/103252657-8ac08f80-4932-11eb-8ed5-6fb58dde7f1d.png)

and some console output.
![image](https://user-images.githubusercontent.com/8261783/103252712-c9564a00-4932-11eb-9578-42622a69e390.png)

my sense is the there might be a device connection that isn't set correctly?  If i figure it out, will add a step to the readme showing a minimal graph for a user to see the awesome.

**Comment by Luxonis-Brandon** [comment]
Thanks for the test/report @eric-schleicher .  I need to test this myself as well, so I don't have advice yet.  And @VanDavv is in Europe so it will be ~5 hours until he's online.

**Comment by VanDavv** [comment]
@eric-schleicher @Luxonis-Brandon this repository should have been archived, it's the first mockup we've made on the GUI.
New and updated repository is here - https://github.com/luxonis/depthai-gui

I'll archive this one, sorry I didn't make it earlier
